name: EasyDate
version: '${project.version}'
main: me.maladik.easydate.EasyDate
api-version: 1.19
description: Adds configurable automatic date in Minecraft! [REQUIRES PLACEHOLDERAPI!]
commands:
  easydate:
    permission: easydate.admin
depend:
  - PlaceholderAPI
